version: '3.9'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - mysql-network

  migrate:
    image: migrate/migrate:v4.15.1
    volumes:
      - ./ddl:/tmp/ddl
    command: ["-path", "/tmp/ddl", "-database",  "mysql://user:password@tcp(mysql:3306)/db", "up"]
    networks:
      - mysql-network

  cli:
    image: mysql:8.0.27
    networks:
      - mysql-network
    command: mysql -hmysql -uuser -ppassword db

  tbls:
    image: ghcr.io/k1low/tbls:v1.54.2
    working_dir: /worker
    volumes:
      - ./doc:/doc
      - ./tools/tbls:/worker
    networks:
      - mysql-network
    command: doc mysql://user:password@mysql:3306/db /doc/database --rm-dist

networks:
  mysql-network:
    driver: bridge
